name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  get-directories:
    name: Get Module Directories
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.find-dirs.outputs.dirs }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find module directories
        id: find-dirs
        run: |
          DIRS=$(ls -d modules/*/ | jq -R -s -c 'split("\n")[:-1]')
          echo "dirs=$DIRS" >> $GITHUB_OUTPUT

  security-scan:
    name: Security Scan
    needs: get-directories
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(needs.get-directories.outputs.directories) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: ${{ matrix.directory }}
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          vuln-type: 'os,library'
          exit-code: '1'
